excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://joyeon.co
title: 허송세월
email: joyeon@gmail.com
author: 조연
description: 반(半) 자발적 FIRE 상태의 기록
paginate: 5
google_analytics: UA-17998259-1
plugins: [jekyll-paginate]

